import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/components/context/UserContext";

export const metadata: Metadata = {
  title: "CGPA Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark flex flex-col items-center min-h-screen bg-background">
        <UserProvider>
          <Navbar />
          <main className="grow w-full py-5 flex justify-center items-center">
            {children}
          </main>
        </UserProvider>
        <Toaster richColors />
        <footer className="border-t p-2 text-center w-full ">
          <p>
            Made with ❤️ by{" "}
            <a href="" target="_blank" rel="noopener noreferrer">
              {" "}
              Christos Uster Biswas
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
